### ISSUE TITLE
help for userguide

### ISSUE THREAD

**Issue by ddlddl58** [ARPA-SIMC/ma_utils#10]
Hi developer,

   Is there a sample file of grib23ddat.inp?

Thank you!

**Comment by enrenr** [comment]
You can build a sample of grib23ddat.inp with the command: grib23ddat.exe -c

**Comment by enrenr** [comment]
Presently, no comprehensive documentation is available for ma_utils, and the comments in source code are mostly in Italian. Please contact me if you need information about a specific program of the suite.

**Comment by ddlddl58** [comment]
> Presently, no comprehensive documentation is available for ma_utils, and the comments in source code are mostly in Italian. Please contact me if you need information about a sp

> Presently, no comprehensive documentation is available for ma_utils, and the comments in source code are mostly in Italian. Please contact me if you need information about a specific program of the suite.

thank u! I read grib23ddat.f90, it can not support presure level at the present stage. For starting the grib23ddat.f90, it need two input file and one inp file. Could you send me a sample of your file _static and file_dat to ddlddl58@gmail.com?
