### ISSUE TITLE
bugs for grib2mm5.f90

### ISSUE THREAD

**Issue by ddlddl58** [ARPA-SIMC/ma_utils#11]
Hi developers,

     I found a bugs in grib2mm5.f90 (located in calmet/src folder). grib2mm5.f90 uses GRIBEX Fortran interface ( legacy in ecmwf grib tools). Is there any possibility to update by using eccodes?

Thank you!

**Comment by brancomat** [comment]
Thanks reporting the issue. Yes, there's an open issue about that (see #8), the plan is to get rid of GRIBEX calls sooner or later.

In the meantime, at the moment it's still possible to compile Emoslib enabling GRIBEX calls (flag `-DENABLE_GRIBEX_ABORT=OFF`, see https://confluence.ecmwf.int/display/EMOS/Emoslib).
And if you're using CentOS or Fedora there's a public repository with packages of both `emoslib` and `ma_utils`: https://copr.fedorainfracloud.org/coprs/simc/stable/
