### ISSUE TITLE
Remove obsolete features

### ISSUE THREAD

**Issue by enrenr** [ARPA-SIMC/ma_utils#7]
- old chimere suite (either replace with current suite or remove)
chimere_env.sh, compile_chimere_chain.sh, crea_input_bc.sh, crea_input_emi.sh, crea_input_meteo.sh, crea_progetto_chimere.sh, estra_grib_cosmo.sh

- calls to vg6d_subarea should be replaced with vg6d_transform --trans-mode=s
./chimere/sh/estra_grib_cosmo.sh
./calmet/sh/run_calmet.sh
./calmet/sh/arkimet_3dd.bash
./arkimet/sh/ak_seriet.ksh
./arkimet/sh/crea_progetto_grid.ksh
./arkimet/sh/ak_getgrib.ksh

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
