### ISSUE TITLE
Remove references to GRIBEX

### ISSUE THREAD

**Issue by enrenr** [ARPA-SIMC/ma_utils#8]
Several (namely 52, see attached list) .f90 codes in ma_utils still use the obsolete GRIBEX functions, that are not supported anymore: these codes should either be re-written or dismissed.
Codes that are not maintained anymore will still be included in ma_utils, but will not be compiled. 
[ma_utils_gribex.txt](https://github.com/ARPA-SIMC/ma_utils/files/3432403/ma_utils_gribex.txt)

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
