### ISSUE TITLE
Labels in sel_punti.f90

### ISSUE THREAD

**Issue by enrenr** [ARPA-SIMC/ma_utils#9]
Add a check in sel_punti.f90, line 257, to prevent the presence of special characters in labels (reason: they may be badly parsed in crea_progetto_point.ksh)

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
